env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  servers: true
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {}
